



default:
	$(MAKE) -C Ylib
	$(MAKE) -C condraw
	$(MAKE) -C convert
	$(MAKE) -C date
	$(MAKE) -C draw
	$(MAKE) -C twmc

clean:
	$(MAKE) -C Ylib clean
	$(MAKE) -C condraw clean
	$(MAKE) -C convert clean
	$(MAKE) -C date clean
	$(MAKE) -C draw clean
	$(MAKE) -C twmc clean


.PHONY: default clean
