extern rw_table *rwtable;
/*extern short *yylhs;
extern short *yylen;
extern short *yydefred;
extern short *yydgoto;
extern short *yysindex;
extern short *yyrindex;
extern short *yygindex;
extern short *yytable;
extern short *yycheck;
extern short *match;
extern char *yymatch;
extern short *yylhs;
extern short *yylen;
extern short *yydefred;
extern short *yydgoto;
extern short *yysindex;
extern short *yyrindex;
extern short *yygindex;
extern short *yytable;
extern short *yycheck;*/
extern unsigned long line_countS;
extern int yylex(FILE *yyin,FILE *yyout);
extern char *yytext;

extern yysvf *yybgin;
extern yysvf *yysvec;
// extern struct yywork *yytop;
extern yywork *yycrank;
extern int *yyvstop;
extern char *yyextra;
