extern rw_table *rwtable;
extern short *yylhs;
extern short *yylen;
extern short *yydefred;
extern short *yydgoto;
extern short *yysindex;
extern short *yyrindex;
extern short *yygindex;
extern short *yytable;
extern short *yycheck;
extern short *match;
extern char *yymatch;
extern short *yylhs;
extern short *yylen;
extern short *yydefred;
extern short *yydgoto;
extern short *yysindex;
extern short *yyrindex;
extern short *yygindex;
extern short *yytable;
extern short *yycheck;
extern unsigned long line_countS;

