void intcompare_overflow(int *side1, int *side2) ;
void print_pads( char *message, PADBOXPTR *array, int howmany );
void align_pads();
void move_clockwise( int pad, int side, int clockwise_side, int moveable_cw );
void move_counterclockwise( int pad, int side, int counterclockwise, int moveable_ccw );
void update_pad_position( PADBOXPTR padptr, int current_side, int move_side );
void expand_core( int side );
void resort_place_array();
void update_pad_groups();
void child_constraints( PADBOXPTR pad, int side, double lb, double ub, BOOL spacing_restricted );
void calc_constraints( PADBOXPTR pad, int side, double *lb, double *ub, BOOL *spacing_restricted, int *lowpos, int *uppos);
void place_variable( int first, int numpads, int side );
BOOL check_overflow( P1(BOOL retain_pad_groups) ) ;
void move_clockwise( P4(INT pad, INT side, INT cw_side, INT moveable_cw) ) ;
void move_counterclockwise( P4(INT pad,INT side,INT ccw_side,INT m_ccw ) ) ;
void update_pad_position( P3(PADBOXPTR pad,INT current_side, INT move_side) );
void expand_core( P1(INT side) ) ;
void intcompare_overflow( P2(INT *side1, INT *side2) ) ;
void update_pad_groups( P1(void) ) ;
void resort_place_array( P1(void) ) ;
void child_constraints(P5(PADBOXPTR pad,INT side,DOUBLE lb,DOUBLE ub,BOOL s));
void place_variable(int first,int numpads,int side);
void calc_constraints( PADBOXPTR pad, int side, double *lb, double *ub, BOOL *spacing_restricted, int *lowpos, int *uppos);
void print_pads( char *message, PADBOXPTR *array, int howmany );
void dimension_pads();
void orient_pads();
