void clear_path_set();
void add2path_set( int path );
INT dcalc_min_path_len();
INT dcalc_max_path_len();
void print_paths( );
void add2path_set( int path );
void clear_path_set();
BOOL member_net_set( int net );
void clear_net_set();
int dcalc_full_penalty();
int calc_incr_time( int cell );
void update_time(int cell);
void add2net_set( int net ) ;
int calc_incr_time2( int cella, int cellb );
void update_time2( int cella, int cellb );
