void init_read_par();
void readparam();
void process_readpar();
void err_msg(char* keyword);
void readpar();
void init_read_par();
void readparam( int parfile );
void process_readpar();
void err_msg(char *keyword);
void init_read_par();
void readparam();
void process_readpar();
void err_msg(char* keyword);
BOOL sc_output();
