
CFLAGS := -I../../include -g

default: assign.o buster.o cleanup.o colors.o deck.o dialog.o draw.o dset.o edcolors.o file.o getftime.o graph.o grid.o hash.o heap.o list.o log.o matrix.o menus.o message.o mst.o mytime.o okmalloc.o path.o plot.o program.o project.o queue.o quicksort.o radixsort.o rand.o rbtree.o relpath.o set.o stat.o stats.o string.o svd.o system.o time.o timer.o trans.o wgraphics.o ydebug.o yreadpar.o 
	ar rv libycad.sys.a assign.o buster.o cleanup.o colors.o deck.o dialog.o draw.o dset.o edcolors.o file.o getftime.o graph.o grid.o hash.o heap.o list.o log.o matrix.o menus.o message.o mst.o mytime.o okmalloc.o path.o plot.o program.o project.o queue.o quicksort.o radixsort.o rand.o rbtree.o relpath.o set.o stat.o stats.o string.o svd.o system.o time.o timer.o trans.o wgraphics.o ydebug.o yreadpar.o 
	ranlib libycad.sys.a
	ar rv libycad.mem.a assign.o buster.o cleanup.o colors.o deck.o dialog.o draw.o dset.o edcolors.o file.o getftime.o graph.o grid.o hash.o heap.o list.o log.o matrix.o menus.o message.o mst.o mytime.o okmalloc.o path.o plot.o program.o project.o queue.o quicksort.o radixsort.o rand.o rbtree.o relpath.o set.o stat.o stats.o string.o svd.o system.o time.o timer.o trans.o wgraphics.o ydebug.o yreadpar.o 
	ranlib libycad.mem.a


clean:
	rm -rf *.o *.a

.PHONY: default clean
