



default:
	$(MAKE) -C Ylib
	$(MAKE) -C date
	$(MAKE) -C twmc
	$(MAKE) -C genrows
	$(MAKE) -C twflow
	$(MAKE) -C mincut
	$(MAKE) -C twsc
	$(MAKE) -C syntax

clean:
	$(MAKE) -C Ylib clean
	$(MAKE) -C date clean
	$(MAKE) -C twmc clean
	$(MAKE) -C genrows clean
	$(MAKE) -C twflow clean
	$(MAKE) -C mincut clean
	$(MAKE) -C twsc clean
	$(MAKE) -C syntax clean

install:
	$(MAKE) -C Ylib install
	$(MAKE) -C date install
	$(MAKE) -C twmc install
	$(MAKE) -C genrows install
	$(MAKE) -C twflow install
	$(MAKE) -C mincut install
	$(MAKE) -C twsc install
	$(MAKE) -C syntax install

.PHONY: default clean install
